import re
import os
import glob
import json
import tempfile
import contextlib
import numpy as np
import multiprocessing
from datasets import load_dataset
from collections import defaultdict
from calculations import calculate_pass_k
from argparse import ArgumentParser



re_name_expected   = re.compile(r"\b([A-Za-z_]\w*)\s*\(")
re_name_generated = re.compile(r"^def\s+(\w+)", re.M)
to_skip   = {"assert","math","isclose","abs","len","set","sorted","list","tuple",
          "str","int","float","round","all","any","print","type","dict","map","filter"}


def match_signature(completion, row):
    expected = next((n for t in row["test_list"] for n in re_name_expected.findall(t) if n not in to_skip), None)
    defined  = set(re_name_generated.findall(completion))
    if not expected or expected in defined or len(defined) != 1:
        return completion
    return completion + f"\n{expected} = {next(iter(defined))}\n"

def build_humaneval(problem, code):
     return problem["prompt"] + code + "\n" + problem["test"] + "\n" + f"check({problem['entry_point']})"
        
def build_mbpp(problem, code):
    parts = [code]
    if problem.get("test_setup_code"):
        parts.append(problem["test_setup_code"])
    parts.extend(problem['test_list'])
    return "\n".join(parts)

@contextlib.contextmanager
def create_tempdir():
    with tempfile.TemporaryDirectory() as dirname:
        with chdir(dirname):
            yield dirname

@contextlib.contextmanager
def chdir(root):
    if root == ".":
        yield
        return
    cwd = os.getcwd()
    os.chdir(root)
    try:
        yield
    except BaseException as exc:
        raise exc
    finally:
        os.chdir(cwd)

def check_correctness(program, results):
    with create_tempdir():
        try:
            exec_globals = {}
            exec(program, exec_globals)
            results.put('passed')
            print("passed")
        except TimeoutError:
            print("timed out")
            results.put("timed out")
        except BaseException as e:
            print('failed')
            results.put(f"failed: {type(e).__name__}: {e}")
        

def execute(program, task_id, timeout):

    manager = multiprocessing.Manager()
    q = manager.Queue()

    p = multiprocessing.Process(target=check_correctness, args=(program, q))
    p.start()
    p.join(timeout= timeout + 1)

    if p.is_alive():
        p.kill()

    result = q.get() if not q.empty() else "timed out"
    return dict(
        task_id = task_id,
        passed = result == 'passed',
        result = result
    )

if __name__ == "__main__":
    multiprocessing.set_start_method("fork")

    parser = ArgumentParser()
    parser.add_argument("--dataset", required=True)
    parser.add_argument("--glob", required=True)
    parser.add_argument("--timeout", required=False, type=float, default=10.0) 

    args = parser.parse_args()

    if args.dataset == "humaneval":
        dataset = load_dataset("openai/openai_humaneval", split='test')
        build = build_humaneval
    elif args.dataset == "mbpp":
        dataset = load_dataset("google-research-datasets/mbpp", "full", split="test")
        build = build_mbpp
    else:
        raise RuntimeError()

    problems = {row['task_id']: row for row in dataset }

    files = sorted(glob.glob(args.glob))

    if not files:
        raise RuntimeError()

    print('loaded in files.')

    by_method = defaultdict(lambda: defaultdict(list))

    for path in files:
        m = re.match(r"samples_\w+?_(.+)_(\d+)_batch(\d+)\.jsonl$", os.path.basename(path))
        method = m.group(1) if m else os.path.basename(path)

        with open(path, "r") as file:
            for line in file:
                rec = json.loads(line)
                by_method[method][rec['task_id']].append(rec["completion"])

    res = defaultdict(list)
    for method in by_method.keys():
        print(f"running programs generated by {method}")
        method_dict = by_method[method]
        for task_id in method_dict:
            for completion in method_dict[task_id]:
                row = problems[task_id]
                if args.dataset == "mbpp":
                    completion = match_signature(completion, row)
                program = build(row, completion)
                res[method].append(execute(program, task_id, args.timeout))
            

    with open(f'execution_results_{args.dataset}.json', "w") as f:
        f.write(json.dumps(res))